const customLightTheme = {
    dark: false,
    colors: {
      background: '#FFFFFF',
      surface: '#FFFFFF',
      'surface-bright': '#FFFFFF',
      'surface-light': '#EEEEEE',
      'surface-variant': '#424242',
      'on-surface-variant': '#EEEEEE',
      'primary-darken-1': '#1F5592',
      'secondary-darken-1': '#018786',
      primary: '#1867C0',
      secondary: '#48A9A6',
      error: '#B00020',
      info: '#2196F3',
      success: '#4CAF50',
      warning: '#FB8C00',
    },
    variables: {
      'border-color': '#000000',
      'border-opacity': 0.12,
      'high-emphasis-opacity': 0.87,
      'medium-emphasis-opacity': 0.60,
      'disabled-opacity': 0.38,
      'idle-opacity': 0.04,
      'hover-opacity': 0.04,
      'focus-opacity': 0.12,
      'selected-opacity': 0.08,
      'activated-opacity': 0.12,
      'pressed-opacity': 0.12,
      'dragged-opacity': 0.08,
      'theme-kbd': '#212529',
      'theme-on-kbd': '#FFFFFF',
      'theme-code': '#F5F5F5',
      'theme-on-code': '#000000',
    }
}

const customDarkTheme = {
    dark: true,
    colors: {
      background: '#0E1117',
      surface: '#181D27',
      'surface-bright': '#333333',
      'surface-light': '#444444',
      'surface-variant': '#616161',
      'on-surface-variant': '#FFFFFF',
      'primary-darken-1': '#1F5592',
      'secondary-darken-1': '#018786',
      primary: '#1867C0',
      secondary: '#48A9A6',
      error: '#CF6679',
      info: '#2196F3',
      success: '#44B78B',
      warning: '#FB8C00',
    },
    variables: {
      'border-color': '#FFFFFF',
      'border-opacity': 0.12,
      'high-emphasis-opacity': 0.87,
      'medium-emphasis-opacity': 0.60,
      'disabled-opacity': 0.38,
      'idle-opacity': 0.04,
      'hover-opacity': 0.04,
      'focus-opacity': 0.12,
      'selected-opacity': 0.08,
      'activated-opacity': 0.12,
      'pressed-opacity': 0.12,
      'dragged-opacity': 0.08,
      'theme-kbd': '#212529',
      'theme-on-kbd': '#FFFFFF',
      'theme-code': '#1E1E1E',
      'theme-on-code': '#FFFFFF',
    }
}

export {
    customLightTheme,
    customDarkTheme
}